### PR TITLE
Add Regex custom element

### PR DESCRIPTION
**Pull request by hzik**
### Motivation

thumbnail for a custom element

### CODE REVIEW

**Review by makma — CHANGES_REQUESTED** [review]
- fix typos in readme: `agains`, `paramters ` 
- make a description of the element in readme more descriptive
- regex.html
-- fix formatting in regex.html
-- why using 3rd party jquery? - DOM manipulation like selectors or show/hide could be nicely managed via plain js eg:
 `.show()` - .style.display = 'block', `.hide()` - `.style.display = 'none'` etc.

**Comment by makma** [comment]
> ### Motivation
> thumbnail for a custom element

?

**Review by makma — CHANGES_REQUESTED** [review]
https://github.com/Kentico/kontent-custom-element-samples/pull/109#pullrequestreview-598281040 still apply

**Comment by yuriys-kentico** [comment]
A better name might be something like "Text element validation extension". Why not also include a text input to make the value colocated? The original element won't be marked as invalid anyway.

A similar element, but for a list, is [List](https://github.com/yuriys-kentico/KenticoKontentKonservatory/tree/main/Client/src/routes/elements/list). That might give you some inspiration.

**Comment by hzik** [comment]
@yuriys-kentico It's not just about marking it as invalidate, it's about preventing editors to publish such an invalid item. And it refers to the original Text box.
@makma review done

**Comment by yuriys-kentico** [comment]
I'm not seeing it preventing publish:
chrome_2021-03-19_08-11-32
Can you send the steps to reproduce what you said?

**Comment by yuriys-kentico** [comment]
Nevermind, I missed a step: making it required did the trick. Maybe add one more step to recommend to add guidelines to make it clear that some other element is actually the one that's invalid.

**Comment by yuriys-kentico** [comment]
You also might consider adding a check for the text element to see if it is available, and otherwise show a friendly message:
```js
function getTextValue(codename) {
  let available = false;

  window.addEventListener(
    'message',
    (e) => {
      if (e.data.data.error) {
        document.getElementById('result').innerHTML = `Can't read '${codename}'!`;
      } else if (!available) {
        CustomElement.getElementValue(codename, (value) => {
          checkRegEx(value);
        });

        available = true;
      }
    },
    true
  );

  window.parent.postMessage({ type: 'get-value-request', data: { codename }, requestId: Date.now() }, '*');
}
```

**Comment by hzik** [comment]
jQuery library was removed even though we link it in our custom element tutorial :) https://docs.kontent.ai/tutorials/develop-apps/integrate/content-editing-extensions

**Review by strizr — APPROVED** [review]

**Pull request merged**
