### PR TITLE
Create LinkChecker.html

### PR DESCRIPTION
**Pull request by hzik**
This custom element s check all links from all rich text elements on the item and check whether they are alive or not.

### CODE REVIEW

**Comment by petrsvihlik** [comment]
@hzik  why using a 3rd party service? why not use something like this: https://www.npmjs.com/package/check-links?

**Comment by ChristopherJennings** [comment]
@petrsvihlik, there's two reasons I'm aware of:

1. Trying to load HTTP over HTTPS (as is the case for custom elements) will result in a mixed content warning/block
2. CORS issues

**Comment by hzik** [comment]
@petrsvihlik @ChristopherJennings yes, it's due to mixed content. I have mentioned that in README. Maybe there are other ways, but this is the one I ended up with :)

**Comment by ChristopherJennings** [comment]
This PR was created before we moved all the code external to this repo. The source for this was published to https://github.com/hzik/LinkChecker

**Pull request closed without merging**
