### PR TITLE
Content insights

### PR DESCRIPTION
**Pull request by strizr**
### Motivation
Adding a docs for a new custom element for Content Insights

### CODE REVIEW

**Comment by Simply007** [comment]
I would rather see this approach instead of placing preview API key right into the JSON config:
* https://docs.kontent.ai/tutorials/develop-apps/integrate/working-with-sensitive-data-in-custom-elements

**Comment by Simply007** [comment]
@ChristopherJennings - what do you think about the closed source approach?

**Comment by strizr** [comment]
> I would rather see this approach instead of placing preview API key right into the JSON config:
> 
> * https://docs.kontent.ai/tutorials/develop-apps/integrate/working-with-sensitive-data-in-custom-elements

We discussed this with Zbysek and it was decided, that preview API key is not really a secret to those who get to work with content models. Also, this is a workaround because our element API can't access rich text directly, which is unfortunate. Also, the workaround is really complicated in my opinion and given the first reason i mentioned hardly worth it in my opinion.

**Comment by strizr** [comment]
> https://kentico.github.io/kontent-custom-element-samples/shared/custom-element.css

Fixed.

**Comment by ChristopherJennings** [comment]
I don't see the sample gallery as a place for closed source custom elements. I think we need a marketplace of some kind to promote both open and closed source elements that are considered production-ready and actively supported. I see this gallery as a simple collection of examples for people to use as a starting point for their own custom elements and closed source CEs don't help with that goal.

Regarding the preview key sensitivity, I think we should treat it with the same level of sensitivity as the secure delivery API. They both act as gatekeepers to the same content (essentially). Just like the secure deliver API key would be hidden from the consumers of the production content, the preview key will normally be hidden from consumers of the preview content. It is a sensitive key that protects content that isn't even approved yet. In some ways, this is even more sensitive than a secure delivery API key.

**Comment by strizr** [comment]
> I don't see the sample gallery as a place for closed source custom elements. I think we need a marketplace of some kind to promote both open and closed source elements that are considered production-ready and actively supported. I see this gallery as a simple collection of examples for people to use as a starting point for their own custom elements and closed source CEs don't help with that goal.

I Agree with this 100%, however, afaik there is no marketplace for custom elements right now, so i was told by PM to put it here, since there is not really any option to put it elsewhere. I'll convey the message, but I don't have better solution.

> Regarding the preview key sensitivity, I think we should treat it with the same level of sensitivity as the secure delivery API. They both act as gatekeepers to the same content (essentially). Just like the secure deliver API key would be hidden from the consumers of the production content, the preview key will normally be hidden from consumers of the preview content. It is a sensitive key that protects content that isn't even approved yet. In some ways, this is even more sensitive than a secure delivery API key.

I understand this, however, i don't see where is the key presented to the consumer? It never leaves the application, it's only visible within the model configuration (which is also sensitive and should be accessible by authorized personnel only) and it can probably be pulled out by investigating the communication between the app and the iframe, which is not that trivial for most people and still is only accessible by content editors. Am I missing something? Thanks!

**Comment by ChristopherJennings** [comment]
I'd be happy to discuss the options for publishing closed source and other production ready custom elements. We need to come up with a solution to promote this and other CEs better. For now the "best" option might be to add it as a blog post on Kontent.ai or include it in the documentation until we have a better solution. 

Yes, you have to be aware that the key is passed to the element, but security through obscurity isn't a proper solution. Yes, it's secure over HTTPS, but an editor (I mentioned "consumer" previously, but editor is more accurate) would be able to capture it in their browser. It is trivial to open dev tools in the browser to capture the preview key and re-use it however you want to. Ultimately, there's not really a "good" solution as it currently stands. We need a way for custom elements to have their own backend that can authenticate with Kontent to enable secure retrieval of these kinds of secret values. In the meantime, I guess I'd be OK with simply disclosing the fact that the Preview key is passed in a way that is not secure.

**Comment by strizr** [comment]
> I'd be happy to discuss the options for publishing closed source and other production ready custom elements. We need to come up with a solution to promote this and other CEs better. For now the "best" option might be to add it as a blog post on Kontent.ai or include it in the documentation until we have a better solution.
> 
> Yes, you have to be aware that the key is passed to the element, but security through obscurity isn't a proper solution. Yes, it's secure over HTTPS, but an editor (I mentioned "consumer" previously, but editor is more accurate) would be able to capture it in their browser. It is trivial to open dev tools in the browser to capture the preview key and re-use it however you want to. Ultimately, there's not really a "good" solution as it currently stands. We need a way for custom elements to have their own backend that can authenticate with Kontent to enable secure retrieval of these kinds of secret values. In the meantime, I guess I'd be OK with simply disclosing the fact that the Preview key is passed in a way that is not secure.

Ok, thanks Chris, makes sense, I'll talk to interested parties and figure out some other solution for now!

**Pull request closed without merging**
