### PR TITLE
Replace UI with a new one that adds filtering

### PR DESCRIPTION
**Pull request by ChristopherJennings**
### Motivation

This replaces the UI with a new one that adds filtering.

### CODE REVIEW

**Comment by ChristopherJennings** [comment]
Still need to update the Readme

**Comment by ChristopherJennings** [comment]
Also just realized that the changes I made for deploying to GH pages wipe out the live versions of the elements, so I'll need to tweak the deploy a bit still.

**Comment by ChristopherJennings** [comment]
Deploy style reverted to old style. Once we remove the old code (Summernote, etc.) we can update the build style.

**Comment by ChristopherJennings** [comment]
Should be fully good to go now.

**Comment by petrsvihlik** [comment]
@ondrabus may I ask you for a review?
please ignore the `/gallery` folder with statically generated output and only review the files in the `/src` and `/gallery-src` folders

**Pull request merged**
