### PR TITLE
Hubspot Forms added + forms category added

### PR DESCRIPTION
**Pull request by strizr**
Adding hubspot forms custom element created by @yuriys-kentico

### CODE REVIEW

**Comment by Simply007** [comment]
@strizr, @yuriys-kentico would it be possible to adjust the Readme of the custom element with the "Example of the output in the Delivery Response" so that the visitor can see right away what he/she can expect?.

I have checked the code, ad it should be based on [IHubSpotForm](https://github.com/yuriys-kentico/KenticoKontentHubspotForms/blob/6e33efd5517d3d7636282e9d1aed3c7a8f947488/Client/src/app/shared/models/hubspot/IHubSpotForm.ts) interface right?

Other than that code looks fine and straightforward - I haven't tested the functionality yet.

**Comment by strizr** [comment]
I have tested it, it works. The output is really based on the IHubSpot interface, however, it's pretty large, so I'm not sure it will help anything - maybe the mention it uses this interface is enough @Simply007 ?

I would add a couple of things into the readme and I will, just not sure what to do with the value output.

**Comment by strizr** [comment]
FYI this is the example object I'm working with: `{"portalId":8736336,"guid":"0d910398-684e-4371-819a-02a6f907bf12","name":"New contact us form (October 30, 2020 11:57:00 AM) ","action":"","method":"POST","cssClass":"hs-form stacked","redirect":"","submitText":"Submit","followUpId":"","notifyRecipients":"12400268","leadNurturingCampaignId":"","formFieldGroups":[{"fields":[{"name":"email","label":"Email","type":"string","fieldType":"text","description":"","groupName":"contactinformation","displayOrder":-1,"required":true,"selectedOptions":[],"options":[],"validation":{"name":"","message":"","data":"","useDefaultBlockList":false,"blockedEmailAddresses":[]},"enabled":true,"hidden":false,"defaultValue":"","isSmartField":false,"unselectedLabel":"","placeholder":"","dependentFieldFilters":[],"labelHidden":false,"propertyObjectType":"CONTACT","metaData":[],"objectTypeId":"0-1"}],"default":true,"isSmartGroup":false,"richText":{"content":"","type":"TEXT"},"isPageBreak":false},{"fields":[{"name":"firstname","label":"First name","type":"string","fieldType":"text","description":"","groupName":"contactinformation","displayOrder":-1,"required":false,"selectedOptions":[],"options":[],"validation":{"name":"","message":"","data":"","useDefaultBlockList":false,"blockedEmailAddresses":[]},"enabled":true,"hidden":false,"defaultValue":"","isSmartField":false,"unselectedLabel":"","placeholder":"","dependentFieldFilters":[],"labelHidden":false,"propertyObjectType":"CONTACT","metaData":[],"objectTypeId":"0-1"}],"default":true,"isSmartGroup":false,"richText":{"content":"","type":"TEXT"},"isPageBreak":false},{"fields":[{"name":"lastname","label":"Last name","type":"string","fieldType":"text","description":"","groupName":"contactinformation","displayOrder":-1,"required":false,"selectedOptions":[],"options":[],"validation":{"name":"","message":"","data":"","useDefaultBlockList":false,"blockedEmailAddresses":[]},"enabled":true,"hidden":false,"defaultValue":"","isSmartField":false,"unselectedLabel":"","placeholder":"","dependentFieldFilters":[],"labelHidden":false,"propertyObjectType":"CONTACT","metaData":[],"objectTypeId":"0-1"}],"default":true,"isSmartGroup":false,"richText":{"content":"","type":"TEXT"},"isPageBreak":false},{"fields":[{"name":"message","label":"Message","type":"string","fieldType":"textarea","description":"","groupName":"contactinformation","displayOrder":-1,"required":false,"selectedOptions":[],"options":[],"validation":{"name":"","message":"","data":"","useDefaultBlockList":false,"blockedEmailAddresses":[]},"enabled":true,"hidden":false,"defaultValue":"","isSmartField":false,"unselectedLabel":"","placeholder":"","dependentFieldFilters":[],"labelHidden":false,"propertyObjectType":"CONTACT","metaData":[],"objectTypeId":"0-1"}],"default":true,"isSmartGroup":false,"richText":{"content":"","type":"TEXT"},"isPageBreak":false}],"createdAt":1604055415344,"updatedAt":1604055436165,"performableHtml":"","migratedFrom":"","ignoreCurrentValues":false,"metaData":[{"name":"lang","value":"en"},{"name":"embedType","value":"REGULAR"}],"deletable":true,"inlineMessage":"Thanks for submitting the form.","tmsId":"","captchaEnabled":false,"campaignGuid":"","cloneable":true,"editable":true,"formType":"HUBSPOT","deletedAt":0,"themeName":"canvas","parentId":0,"style":{"fontFamily":"arial, helvetica, sans-serif","backgroundWidth":"100%","labelTextColor":"#33475b","labelTextSize":"13px","helpTextColor":"#7C98B6","helpTextSize":"11px","legalConsentTextColor":"#33475b","legalConsentTextSize":"14px","submitColor":"#ff7a59","submitAlignment":"left","submitFontColor":"#ffffff","submitSize":"12px"},"isPublished":true,"publishAt":0,"unpublishAt":0,"publishedAt":0,"multivariateTest":{"variants":[],"startAtTimestamp":0,"endAtTimestamp":0,"winningVariantId":"","finished":false,"controlId":""},"kickbackEmailWorkflowId":0,"kickbackEmailsJson":"","customUid":"","createMarketableContact":true,"editVersion":0,"thankYouMessageJson":"","themeColor":"","alwaysCreateNewCompany":true,"internalUpdatedAt":1604055436165}`

**Comment by Simply007** [comment]
If you format the JSON it does not look that bad:

```json
{
  "portalId": 8736336,
  "guid": "0d910398-684e-4371-819a-02a6f907bf12",
  "name": "New contact us form (October 30, 2020 11:57:00 AM) ",
  "action": "",
  "method": "POST",
  "cssClass": "hs-form stacked",
  "redirect": "",
  "submitText": "Submit",
  "followUpId": "",
  "notifyRecipients": "12400268",
  "leadNurturingCampaignId": "",
  "formFieldGroups": [
    {
      "fields": [
        {
          "name": "email",
          "label": "Email",
          "type": "string",
          "fieldType": "text",
          "description": "",
          "groupName": "contactinformation",
          "displayOrder": -1,
          "required": true,
          "selectedOptions": [],
          "options": [],
          "validation": {
            "name": "",
            "message": "",
            "data": "",
            "useDefaultBlockList": false,
            "blockedEmailAddresses": []
          },
          "enabled": true,
          "hidden": false,
          "defaultValue": "",
          "isSmartField": false,
          "unselectedLabel": "",
          "placeholder": "",
          "dependentFieldFilters": [],
          "labelHidden": false,
          "propertyObjectType": "CONTACT",
          "metaData": [],
          "objectTypeId": "0-1"
        }
      ],
      "default": true,
      "isSmartGroup": false,
      "richText": {
        "content": "",
        "type": "TEXT"
      },
      "isPageBreak": false
    },
    {
      "fields": [
        {
          "name": "firstname",
          "label": "First name",
          "type": "string",
          "fieldType": "text",
          "description": "",
          "groupName": "contactinformation",
          "displayOrder": -1,
          "required": false,
          "selectedOptions": [],
          "options": [],
          "validation": {
            "name": "",
            "message": "",
            "data": "",
            "useDefaultBlockList": false,
            "blockedEmailAddresses": []
          },
          "enabled": true,
          "hidden": false,
          "defaultValue": "",
          "isSmartField": false,
          "unselectedLabel": "",
          "placeholder": "",
          "dependentFieldFilters": [],
          "labelHidden": false,
          "propertyObjectType": "CONTACT",
          "metaData": [],
          "objectTypeId": "0-1"
        }
      ],
      "default": true,
      "isSmartGroup": false,
      "richText": {
        "content": "",
        "type": "TEXT"
      },
      "isPageBreak": false
    },
    {
      "fields": [
        {
          "name": "lastname",
          "label": "Last name",
          "type": "string",
          "fieldType": "text",
          "description": "",
          "groupName": "contactinformation",
          "displayOrder": -1,
          "required": false,
          "selectedOptions": [],
          "options": [],
          "validation": {
            "name": "",
            "message": "",
            "data": "",
            "useDefaultBlockList": false,
            "blockedEmailAddresses": []
          },
          "enabled": true,
          "hidden": false,
          "defaultValue": "",
          "isSmartField": false,
          "unselectedLabel": "",
          "placeholder": "",
          "dependentFieldFilters": [],
          "labelHidden": false,
          "propertyObjectType": "CONTACT",
          "metaData": [],
          "objectTypeId": "0-1"
        }
      ],
      "default": true,
      "isSmartGroup": false,
      "richText": {
        "content": "",
        "type": "TEXT"
      },
      "isPageBreak": false
    },
    {
      "fields": [
        {
          "name": "message",
          "label": "Message",
          "type": "string",
          "fieldType": "textarea",
          "description": "",
          "groupName": "contactinformation",
          "displayOrder": -1,
          "required": false,
          "selectedOptions": [],
          "options": [],
          "validation": {
            "name": "",
            "message": "",
            "data": "",
            "useDefaultBlockList": false,
            "blockedEmailAddresses": []
          },
          "enabled": true,
          "hidden": false,
          "defaultValue": "",
          "isSmartField": false,
          "unselectedLabel": "",
          "placeholder": "",
          "dependentFieldFilters": [],
          "labelHidden": false,
          "propertyObjectType": "CONTACT",
          "metaData": [],
          "objectTypeId": "0-1"
        }
      ],
      "default": true,
      "isSmartGroup": false,
      "richText": {
        "content": "",
        "type": "TEXT"
      },
      "isPageBreak": false
    }
  ],
  "createdAt": 1604055415344,
  "updatedAt": 1604055436165,
  "performableHtml": "",
  "migratedFrom": "",
  "ignoreCurrentValues": false,
  "metaData": [
    {
      "name": "lang",
      "value": "en"
    },
    {
      "name": "embedType",
      "value": "REGULAR"
    }
  ],
  "deletable": true,
  "inlineMessage": "Thanks for submitting the form.",
  "tmsId": "",
  "captchaEnabled": false,
  "campaignGuid": "",
  "cloneable": true,
  "editable": true,
  "formType": "HUBSPOT",
  "deletedAt": 0,
  "themeName": "canvas",
  "parentId": 0,
  "style": {
    "fontFamily": "arial, helvetica, sans-serif",
    "backgroundWidth": "100%",
    "labelTextColor": "#33475b",
    "labelTextSize": "13px",
    "helpTextColor": "#7C98B6",
    "helpTextSize": "11px",
    "legalConsentTextColor": "#33475b",
    "legalConsentTextSize": "14px",
    "submitColor": "#ff7a59",
    "submitAlignment": "left",
    "submitFontColor": "#ffffff",
    "submitSize": "12px"
  },
  "isPublished": true,
  "publishAt": 0,
  "unpublishAt": 0,
  "publishedAt": 0,
  "multivariateTest": {
    "variants": [],
    "startAtTimestamp": 0,
    "endAtTimestamp": 0,
    "winningVariantId": "",
    "finished": false,
    "controlId": ""
  },
  "kickbackEmailWorkflowId": 0,
  "kickbackEmailsJson": "",
  "customUid": "",
  "createMarketableContact": true,
  "editVersion": 0,
  "thankYouMessageJson": "",
  "themeColor": "",
  "alwaysCreateNewCompany": true,
  "internalUpdatedAt": 1604055436165
}
```

---

It is possible to cut out some parts out like i.e.:
```
{
  "portalId": 8736336,
  "guid": "0d910398-684e-4371-819a-02a6f907bf12",
  "name": "New contact us form (October 30, 2020 11:57:00 AM) ",
  "action": "",
  "method": "POST",
  "cssClass": "hs-form stacked",
  "redirect": "",
  "submitText": "Submit",
  "followUpId": "",
  "notifyRecipients": "12400268",
  "leadNurturingCampaignId": "",
  "formFieldGroups": [
    {
      "fields": [
        {
          "name": "email",
          "label": "Email",
          "type": "string",
          "fieldType": "text",
          "description": "",
          "groupName": "contactinformation",
          "displayOrder": -1,
          "required": true,
          "selectedOptions": [],
          "options": [],
          "validation": {
            "name": "",
            "message": "",
            "data": "",
            "useDefaultBlockList": false,
            "blockedEmailAddresses": []
          },
          "enabled": true,
          "hidden": false,
          "defaultValue": "",
          "isSmartField": false,
          "unselectedLabel": "",
          "placeholder": "",
          "dependentFieldFilters": [],
          "labelHidden": false,
          "propertyObjectType": "CONTACT",
          "metaData": [],
          "objectTypeId": "0-1"
        }
      ],
      "default": true,
      "isSmartGroup": false,
      "richText": {
        "content": "",
        "type": "TEXT"
      },
      "isPageBreak": false
    }
    // ....
  ],
  "createdAt": 1604055415344,
  "updatedAt": 1604055436165,
  "performableHtml": "",
  "migratedFrom": "",
  "ignoreCurrentValues": false,
  "metaData": [
    {
      "name": "lang",
      "value": "en"
    },
    {
      "name": "embedType",
      "value": "REGULAR"
    }
  ],
  // ...
}
```

---

Or if you think it is still too much (and I agree and am fine with that), I would definitely add a link to `IHubSpotForm` and to 
`https://legacydocs.hubspot.com/docs/methods/forms/forms_overview` to let people see what they can expect.

Something like:

## Example output

The output is based on [IHubSpotForm](./Client/src/app/shared/models/hubspot/IHubSpotForm.ts) which is based on the official [Hubspot Form object scheme](https://legacydocs.hubspot.com/docs/methods/forms/forms_overview).

**Comment by Simply007** [comment]
As agreed - let's wait for @strizr to finish a review over all custom elements.

@strizr - you could convert this pull request to draft, or close it for now if you want.

**Comment by strizr** [comment]
New version of the element will be added soon

**Comment by yuriys-kentico** [comment]
By the way, this is old; that repository is at risk of being archived (made private).

**Pull request closed without merging**
